### ISSUE TITLE
💸 Tech Debt - Improve page performance (Investigate App Router)

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1078]
**Description**  
Currently, due to the live stream banner, our website's performance is going down, to improve the performance we need to investigate if we can implement a server-side cache or app routing. 

```[tasklist]
### Tasks
- [x] Investigate if app router is compatible with Tina
```

**Comment by Harry-Ross** [comment]
cc @wicksipedia @bradystroud 

Migrating to the app router would be an quite large task - but it can be done incrementally with select routes for testing. 

Reasons for:
1. Can make fetches to GraphQL/other data sources inside components without need to worry about adding performance overhead
2. Potentially faster - SSR everything may result in performance gains
3. Less need to rely on insecure API routes - fetching can be build directly into component
4. Caching fetched data natively built into `fetch` as a polyfill in server components

Reasons against:
1. Not the recommended way of using TinaCMS (minimal support, many bugs using it)
  a. Visual editing is currently not working/very challenging to implement, as `"use client"` must be applied in order to be able to use the `useTina` React hook
  b. See https://discord.com/channels/835168149439643678/1115679733347254323/1115729732651196489 for the TinaCMS devs experience with app router
3. Not a lot of resources with the app router as it is still very new 
5. Much easier to do static generation (`getStaticProps`) - new way of doing it will be change in paradigm (https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#static-site-generation-getstaticprops)
6. Refactoring needed of a lot of what we have already written (`"use client"`, etc.) to still work
  a. Main reason is we cannot use basic hooks such as `useEffect` and `useRouter` which are a large part of our code using the app router

In my opinion, I believe we should hold off on migrating to App Router until there is greater support for it, but keep in mind when developing components that we may be moving to it in the future.

https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration

**Comment by Harry-Ross** [comment]
Status update:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/2bff05c0-bdac-49de-8ba7-078ebdc4f969)

**Figure: working on app router with a lot of removal of functionality**

* Got base page working with a large amount of "use client", which means a lot of the benefits of RSC cannot be realised 
* Had to comment out all uses of `useRouter` in components that are referenced by TinaMarkdown
* Not clear whether `tinaField` can still be used by RSC

**Comment by Harry-Ross** [comment]
Another point:

Even if we were to adopt RSC for our components, these server components would not be able to be rendered with the `<TinaMarkdown>` component, as that is client component, which as per https://nextjs.org/docs/getting-started/react-essentials#nesting-server-components-inside-client-components, server components cannot be imported into client components.

Additionally, as per the Tina Discord (https://discord.com/channels/835168149439643678/1130894388080418816/1130913227216277608) it appears their main focus on using NextJS with Tina is the Pages router.

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, this is ready to close this pending @wicksipedia's approval

**Comment by Harry-Ross** [comment]
As per my conversation with @wicksipedia, as Tina does not natively support the App router without excessive `"use client"`s, therefore is viable for the project at this time.
