### ISSUE TITLE
🐛 SSW Website's Cookie not set in the Header

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.Website#1146]
cc @adamcogan @william-liebenberg @wicksipedia @bradystroud @Harry-Ross 

**Describe the bug**
As per my conversation with @Harry-Ross , when running Artillery Load Test on SSW Website, it's reporting that the web's Cookie has not been set in the host's domain. It is working on SSW Rules and People however.

See [link](https://javascript.info/cookie#:~:text=Cookies%20are%20usually%20set%20by,using%20the%20Cookie%20HTTP%2Dheader.) to see how Cookie should be set in its HTTP-Header

**To Reproduce**
1. Run Artillery Load Test on SSW Website
2. See error

**Screenshots/Video**
<img width="1059" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/67776356/c035a32f-1dec-49e6-86dd-62c95fd673fd">

**Figure: Artillery error log when running on SSW Website**

**Comment by Harry-Ross** [comment]
@tombui99 and I investigated - we found that in the "Set-Cookie" header in the HTTP request from www.ssw.com.au, there was a cookie set that was messing with Artillery - `Domain` was set to the Azure domain of the website, and thus Artillery was throwing an error that the Domain value was set incorrectly.

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/5d51f19c-b280-404a-a91d-31f5a03b2c4a)
**Figure: The erraneous cookie in question**

This was fixed by changing CodeAuditor's request URL to the Azure URL instead of ssw.com.au

**Comment by wicksipedia** [comment]
Can you disable ARRAffinity so that the cookie is no longer generated?
We shouldn't need this for the site

**Comment by Harry-Ross** [comment]
@wicksipedia I tried to turn off ARRAffinity as a part of the investigation, but I didn't have the priveleges to change it.

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/4220875a-9030-45fd-b916-5b101965117e)

**Comment by wicksipedia** [comment]
It's driven through bicep, need to change it there

**Comment by Harry-Ross** [comment]
![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/e2c5307f-c5d4-449d-9621-be40e32c9181)

Artillery now runs after disabling AARAffinity.
