### ISSUE TITLE
💸 Tech Debt - Improve "Upcoming Events" section

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#1148]
cc @bradystroud @BrookJeynes @jaydenalchin @adamcogan @amankumarrr 

**Description**  

"Upcoming Events" section is currently too cluttered...

**Proposed solution**  

- [ ]  Action the changes in this video (same as below): https://www.loom.com/share/4234abbbb4454675a83e87d4d4772e04  

1. Add padding to article (using class `p-4`)
2. Replace overall text padding (`px-6`) with a margin left (`ml-4`)
3. Move the countdown tag "DAYS TO GO" to come 1st
    - change margin from left to right (from `ml-2` to `mr-1`)

4. Reduce "time" text size ( `text-xs`)  - This is because of https://github.com/SSWConsulting/SSW.Website/issues/1147

---

<img width="498" alt="Screenshot 2023-07-31 at 12 42 04 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/66cfa786-0185-46e9-81af-7c82e8947064">

**Figure: Current "Upcoming Events" section** 

<img width="508" alt="Screenshot 2023-07-31 at 1 03 54 PM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/83c550d2-196b-4718-b5c7-bdaf01ca6d39">

**Figure: Proposed "Upcoming Events" section after changes**

**Comment by jaydenalchin** [comment]
@tiagov8 Huge improvement to the events list above. What do you think about an alternate solution taking advantage of these cards?

<img width="468" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/75593567/c3ef408b-49a4-4edf-a920-d74b9e25ecc7">

**Figure: Mockup - Upcoming event card list**

**Comment by tiagov8** [comment]
> @tiagov8 Huge improvement to the events list above. What do you think about an alternate solution taking advantage of these cards?

I ❤️ it!

@BrookJeynes / @amankumarrr 

1. Please prioritize this with the PO
2. Make sure the changes reflect well on mobile 

Let me know if you need any help with the CSS

**Comment by amankumarrr** [comment]
@jaydenalchin I really love this design, I'm thinking to add some icons to represent persons, and `ongoing events` with `green` color instead of `sswRed`, what's your thoughts on it?

<img width="204" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/537aa294-edab-4eb3-a7bd-6ad37966a930">

**Figure: Ongoing event with green background and presenters with user and users icons**

**Comment by jaydenalchin** [comment]
> @jaydenalchin I really love this design, I'm thinking to add some icons to represent persons, and `ongoing events` with `green` color instead of `sswRed`, what's your thoughts on it?

I'm impressed with the quick turn around @amankumarrr and this is looking like an excellent update! 

1. The user icons are a great idea but in this context (compact content) I don't think we should add too many small UI  elements like these in order to minimize cognitive load. 
2. I prefer the simplicity of TODAY vs NOW RUNNING. 
3. I don't mind the colour highlighting current/next event at all! However, there's a problem in colour contrast with white text on this green - the text would need to be black - which makes this feel too different & out of place to me. We could spend some time finding the right alternative bg colour but it might not be worth the ROI. 

<img width="508" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/75593567/046afbee-1b1f-4fce-bc1d-e8a59859491e">

**Figure: Green pill with higher colour contrast** 

4. Not related to the above - please make sure the cards have a 4px border radius. Everything else is awesome!

**Comment by amankumarrr** [comment]
@jaydenalchin 
> TODAY vs NOW RUNNING

We are showing `NOW RUNNING` for the events that runs for 2 days, for 1 day, we are showing `TODAY`, do you think we should change this?

**Comment by tiagov8** [comment]
Hi @amankumarrr / @jaydenalchin 

For the green label, I'd follow exactly what we have on homepage as OPEN:

<img width="729" alt="Screenshot 2023-08-01 at 10 58 20 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/91c3f460-1415-47ab-a7f1-779964caa057">

PS. Looking at [your screenshot above](https://github.com/SSWConsulting/SSW.Website/issues/1148#issuecomment-1659501571)... I think we need to lose the light grey background

**Comment by tiagov8** [comment]
@amankumarrr 

> We are showing NOW RUNNING for the events that runs for 2 days, for 1 day, we are showing TODAY, do you think we should change this?

I like this feature

**Comment by jaydenalchin** [comment]
> Hi @amankumarrr / @jaydenalchin
> 
> For the green label, I'd follow exactly what we have on homepage as OPEN:


Agreed we should ideally use a consistent colour. 

However, white text with the green from OPEN also fails to meet colour contrast & readability standards. 

![image](https://github.com/SSWConsulting/SSW.Website/assets/75593567/84e06808-943d-4104-babf-77d178be4c7c)

**Figure: OPEN green colour contrast**

For the record I still like the idea of using TimePro's teal accent colour for things like this, we already use it across that whole platform. Noting that it also should be darkened slightly to meet min contrast (and that's likely out of scope for this issue)

![image](https://github.com/SSWConsulting/SSW.Website/assets/75593567/be8a8956-cc72-410c-a81b-b38d55948e4f)

**Figure: TimePro colour contrast (dark variant)**

**Comment by tiagov8** [comment]
Hey @jaydenalchin 

I'm happy to use the teal from TimePro (or even make it darker if needed)... 

Once it's defined... Can we have tasks to make it consistent everywhere?

- "TODAY" labels in EVENTS
- "OPEN" labels in OFFICES WIDGET
- In here: https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Colors 
- And green buttons: https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Buttons
- And "good" in lists and captions: https://www.ssw.com.au/ssw/company/Web-Reference.aspx#Lists 
- And Rules green tick: https://raw.githubusercontent.com/SSWConsulting/SSW.Rules/main/static/assets/Good.gif
