### ISSUE TITLE
🐛 Create Leads - Missing emails from old ContactUs page

### ISSUE THREAD

**Issue by samsmithssw** [SSWConsulting/SSW.Website#1306]
Any email that has come from the old Contact Us page https://www.ssw.com.au/ssw/Company/ContactUs.aspx has not been sent through to the Account Managers.

As per my conversation with @amankumarrr , this page has been up for a long time so a lot of potential leads may have fallen through the net since the new Create Lead flow was created.

Every lead should create a corresponding email to the Account Managers so that they can call the contact ASAP.

**Comment by amankumarrr** [comment]
@adamcogan @wicksipedia @bradystroud  @Marxoz 

Checked by @samsmithssw and @bradystroud 

On investigation, I found out that this has been happening since our fix with issue #671 on 23rd May 2023. A list of missing leads has been circulating with the subject "SSW Contact Us page - Possible missed leads". It seems like 5 possible leads that we have missed after a scan from that list by @Levijj22.


**Why did it happen**
Our CRM records were generated through the legacy endpoint, and the CRM's trigger mechanism facilitated email notifications. However, due to reports of duplicated emails, we opted to deactivate the CRM's notification feature. This was especially relevant as our Power Automate Flow was concurrently responsible for sending emails. Unfortunately, we didn't check that the old endpoint was being used anywhere and we didn't test it after the change, we only tested the new one because we didn't realize that this change would impact the old pages. 

**Power Automate Flow**
Our current Power Automate flow, initiates the creation of a lead in CRM, upon successful execution, it dispatches email notifications to all account managers. In case of any failure in creating a record in CRM, it will also send out an email to the SSW team. We also catered to a case when our flow becomes inaccessible then we will receive an email from Azure. 


**Mitigation and Future Precautions**
With the migration process:
-  We should zz the pages that we have migrated to show the visibility and work on the remaining ones - #1263 
-  Before turning off or making any feature redundant for the old site, we should identify all the possible areas where it might impact.

We have also created these issues to follow up: 
 - https://github.com/SSWConsulting/SSW.Website/issues/1310
 - https://github.com/SSWConsulting/SSW.Website/issues/1313
