### ISSUE TITLE
🐛 .NET UG - Client-Side Routing Error on 404

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#1644]
Whenever I access a 404 on `netug/abc123`, it returns a weird 500 application error. This is likely due to some of the logic in `getStaticProps` or `getStaticPaths` not displaying a 404 on a not found path.

![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/ce69cd41-aac4-49e4-9d1b-5da4316af683)

```[tasklist]
### Tasks
- [ ] Fix the problem in `pages/netug/[[...filename]].tsx`
```

**Comment by jeoffreyfischer** [comment]
**Description**:
When a user accesses a non-existing path (e.g. netug/abc123), it returns a 500 status coder instead of a 404.

**Solution**:
The fallback property in getStaticPaths needs to be set from 'true' to 'false'. Now, the app returns a 404 (see **Figure**).

- Affected routes: `/netug` 

- Fixed #1644

**Screenshots**:

![website-PR-003](https://github.com/SSWConsulting/SSW.Website/assets/106663901/c6a60f1d-9570-4840-8265-25a4106d8ef2)
**Figure**: A 404 status code is returned when accessing a non-existing page
