### ISSUE TITLE
🐞 BUG - Events - shows incorrect start/end dates (especially on facebook ads)

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#1664]
When I look at the event page via a facebook ad - it shows the wrong dates for Melb & Syd (should be 13-14 & 16-17)

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/442ebded-f509-4465-ba64-e5c412e610a8)

When I go to the page directly, it shows the right dates, but if I refresh.... I can see the dates flicker from wrong to right

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/668b8122-d174-49d0-8754-9ca27351e2a8)
**Figure: flicker**

**Comment by bradystroud** [comment]
@jeoffreyfischer and I worked on this together.

There was 2 separate problems.
explanation - https://youtu.be/Nc8EXYLxlc4

### 1 - TinaCMS Bug - Datetime changes when you click save (not fixed)
reported to Tina - tinacms/tinacms#4313
Video explaining problem (2 min) - https://www.youtube.com/watch?v=yKRLiA0pM50

This was causing our dates to save wrong, we fixed it in #1669 

### 2 - Website Bug - `timeFormat` included date
Fixed in #1671 

This was causing the date to show as time on the TinaCMS UI

![](https://github.com/SSWConsulting/SSW.Website/assets/38869720/626b20ad-1976-4051-bb21-ab386127795a)
**Figure: The time was set to the date 🤔 (e.g. 29th Nov 2023 was showing 11:29:23)**

**Comment by bradystroud** [comment]
Hey @wicksipedia 

✅ As per our conversation, this is done.
See above comment for info

<img width="1523" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/604ba41c-2792-4d9a-823f-a9aef822593b">

**Figure: Workshop dates line up with our SharePoint calendar**
