### ISSUE TITLE
🐛Tina CMS - Client Page is not editable 

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#1793]
**Describe the bug**
If an attempt is made to edit the `/company/clients` page in Tina, it results in a white screen.

**To Reproduce**
1. Login to `/admin/index.html#/~/company/clients`

**Expected behavior**
It should show the client page in Tina CMS for editing 

**Screenshots/Video**
<img width="845" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/673b0ab6-fb58-44a0-81ae-26beda4e249f">

**Figure: Client page on production showing white screen**

**Comment by Harry-Ross** [comment]
I decided on using the glob pattern `@(case-study|index|clientCategories)/*` instead of `*/*` (which would catch everything in a subfolder) just in case someone would want to create a company page in a subdirectory. See below for an example:

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/986bf13c-f4cc-458d-8e81-67e7792bc8da)
**Figure: Using this instead of */*, which would catch the second last case**
