### ISSUE TITLE
🔥🐛 Broken Page - UI/UX Design

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website#1985]
(Checked by @william-liebenberg)
**Describe the bug**

The UI/UX Design page is currently not working. It loads, and then crashes :(

**To Reproduce**
1. Visit https://www.ssw.com.au/consulting/ui-ux-design 

**Expected behavior**

The UI/UX Design marketing page should load.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
Remember to mark the area in the application thats impacted.

![image](https://github.com/SSWConsulting/SSW.Website/assets/17246482/061e4905-59bd-4a4a-bc9b-fa8734803f67)
**_Figure: Page crashes_**

**Comment by amankumarrr** [comment]
@wicksipedia @bradystroud 

Hi @tkapa 

The problem has been resolved. The error arose because we inadvertently passed an `undefined` prop to the Next Link component; it expected a string for its `href` attribute. After ensuring that the correct string type was provided, the issue was successfully fixed. 

To avoid this happening, more guards are being added to the link component. 

<img width="460" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/9fbd51fc-79a7-4a63-9663-50b0a4372195">

**Figure: Changes that fixed the issue**
