### ISSUE TITLE
🧪 Experiment - App Router w/ Preview Route

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#2168]
cc @wicksipedia 

In spite of previous failed attempts to migrate to the app router, I've thought of a way it can be done. As per https://github.com/SSWConsulting/SSW.Website/issues/2115#issuecomment-1940200744, the problem is that using `useTina` requires a client-side environment. This means the entire page would have to be client-side rendered to be able to use visual editing in `/admin`. 

A workaround to this is creating two separate routes:

* Server-side - `/page-route-here`
* Client-side  - `/preview/page-route-here` (would have to be hidden from SEO/public)

Then, TinaCMS can load the client-side page as a preview, and still have visual editing capabilities, without the server-rendered page being impacted by use of `useTina`. 

Previous attempt: https://github.com/SSWConsulting/SSW.Website/issues/1078

```[tasklist]
### Tasks
- [x] Create a POC for an app router page
```

**Comment by Harry-Ross** [comment]
As per my conversation with @amankumarrr, the work currently done on this PR demonstrates a basic proof of concept. 

We discovered that the visual editing with TinaCMS works with this PoC. 

We also attempted to fix the issue with use of `export const dynamicParams = false;` using various options associated with `dynamic` to not much avail. Currently, there is a 404 on the `/products/rewards` page that can be fixed if you force the page to be dynamic, but this seems like a bad option because it means that there will be unnecessary requests to TinaCMS.

**Comment by amankumarrr** [comment]
@wicksipedia 

On further investigation, I found that the i18n option is only compatible with page routing. For App Routing, we need to use react-i18n. I've tried removing that config from next.config, and it seems to be working the same as it was for page routing.

https://github.com/vercel/next.js/discussions/55531#discussioncomment-7378305

**Comment by amankumarrr** [comment]
The issue arises from an incompatibility between i18n (internationalization) and App Routing. When dynamicParam is set to true, it allows static pages to be generated on request and cached. However, with internationalization enabled, setting dynamicParam to false caused pages to be generated during build time, resulting in 404 errors.

To address this, we have two options:

Set dynamicParam to true, generating pages on request, which resolves the issue. However, this may introduce a downside as pages are generated on request instead of during build time.
Remove internationalization from the configuration entirely, which resolves the issue but also removes internationalization functionality.

**Comment by amankumarrr** [comment]
As per my conversation with @wicksipedia, considering that we're not utilizing internationalization on our website, we can safely remove the i18n configuration from our setup. This should resolve the issue with generating static pages during build time for the App Routing.

**Comment by amankumarrr** [comment]
Done - we've successfully migrated the /products route to App Routing. Moving forward, we'll closely monitor the traffic on this route and, after a few weeks, we will begin migrating other pages incrementally. For the next route, here is the issue - https://github.com/SSWConsulting/SSW.Website/issues/2600
