### ISSUE TITLE
⚠️ Megamenu - hydration errors are causing lighthouse scores to tank

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2386]
When I was investigating #2385 and tried to run a lighthouse check locally for `/consulting/sharepoint` - hydration errors cause the score to tank

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/9dbc695f-23d4-4348-8ab1-2e924215b7c5)

![Image](https://github.com/SSWConsulting/SSW.Website/assets/600044/093340a4-602b-4513-8bf3-c4b8f02e90b2)

```[tasklist]
### Tasks
- [x] Fix hydration errors with megamenu
- [x] Investigate other hydration errors still occurring on production
```

**Comment by Harry-Ross** [comment]
![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/895bd19b-2092-4b01-8744-71efafea1102)
**Figure: Hydration errors still present on ssw.com.au**

As there is still hydration errors occurring on production, I ran a diff checker on the server-rendered HTML of the production environment and PR environment and found there was only 1 difference: 

![Image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/78563b77-2dac-4ee9-b2cf-7d309402a771)
**Figure: Source of ssw.com.au on the left (US timezone), source of a PR deployment (AU timezone)**

This should be fixed by moving timezone logic to client-side rendering.
