### ISSUE TITLE
🐛 BUG - Can't add categories to a client

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Website#2412]
cc @Harry-Ross 

**Describe the bug**

When I click the + button to add a category... it gives me a 404!

- [ ] 1. Please consider moving this to the Tina repo
- [x] 2. Please investigate and fix

<img width="1179" alt="Screenshot 2024-04-03 at 11 41 59 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/888d649b-6daf-4354-bf34-d78575a13d57">

<img width="1455" alt="Screenshot 2024-04-03 at 11 42 12 AM" src="https://github.com/SSWConsulting/SSW.Website/assets/12601228/258f6620-1583-47fa-8e56-295aa29d70d3">

---

**Note:** I ended up adding the categories directly in GitHub: https://github.com/SSWConsulting/SSW.Website/pull/2413/commits/1e6a70123e8a68b93c7dfc9eae8fc802184c7cb1

**Comment by andrewwaltosssw** [comment]
Fixed by adding optional chaining to Category property.

Root cause not fully understood - can guess that the data (source from `clients.mdx` file) is not retrieved by Tina at time of render resulting in error trying to access property of null value.

![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/1a47fd7e-3f4f-41f5-91b1-641b37e6f7d0)
**Figure: [Current Prod] Admin dashboard for /company/client page after clicking "+" to Categories**


![image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/25cba338-5add-44ce-bea5-0ea1b712dde7)
**Figure: [Previously on local] Details of the error when encountered on local server**

**Comment by andrewwaltosssw** [comment]
![donegif2](https://github.com/SSWConsulting/SSW.Website/assets/87786621/faac8d93-8659-44bf-a944-57f3e09dad3f)

**Figure: Done gif showing the page not failing when adding a category**
