### ISSUE TITLE
🚧 Failed requests - Investigate high spike

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#2499]
**Description**
This week, SSW Website had a high spike in the failed requests count - 154k (see Figure)
Link: [Azure portal - Failed requests](https://portal.azure.com/#view/AppInsightsExtension/UsageNotebookBlade/ComponentId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2FresourceGroups%2Fssw.com.au%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2FappInsight-sswwebsite-9eb3/ConfigurationId/%2Fsubscriptions%2Fb8b18dcf-d83b-47e2-9886-00c2e983629e%2Fresourcegroups%2Fssw.com.au%2Fproviders%2Fmicrosoft.insights%2Fworkbooks%2F0be4e8a1-c1e9-4043-b8c1-167bb8d73085/Type/workbook/WorkbookTemplateName/Failed%20Requests%20-%20With%20less%20noise)
Note: a lot of the issues seem to be coming from the Newsletter pages (see Figure)

**Screenshots**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/f854d894-68a5-4005-b624-05037b8f9b68)
**Figure: Failed request high spike from last week**

![Image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/5f9d594a-c02f-430f-9c71-2a39978872c1)
**Figure: Most issues come from the Newsletter pages**

Tasks

- [ ] Investigate the origin of these failed requests spikes
- [ ] If possible, fix the issue

**Comment by andrewwaltosssw** [comment]
Findings on the bulk of these failed requests related to newsletters:
- ~55,000 opeartion_Name contains `htm.json` which is not a valid resource on our site
- All of the above contain client_OS `Linux 5.15.145.2-1.cm2`
- ~10,000 operation_Name contains `sleep` or `select` in query string

![Image](https://github.com/SSWConsulting/SSW.Website/assets/87786621/cf31c514-f626-4987-8559-1c5f35ae3700)
**Figure: Weird requests**

This is from over one month ago and we have not seen this level of spike since then. Likely these failures were from a pen attempt
