### ISSUE TITLE
🗃️ Archive Pages - Archive /standards

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Website#2561]
cc: @Calinator444 @fenix2222 @tiagov8 

As per my conversation with @adamcogan, in order to expedite switching off the VM, we plan on archiving `/standards` to static HTML as a quick fix as it takes longer to migrate the standards to SSW.Rules.

The standards will still be migrated to SSW.Rules, just not part of this PBI.

**Comment by Calinator444** [comment]
I've ran the migration script on the pages, using this to check which pages are up to scratch (by folder): 
- [x] root
- [x] better-software-suggestions
- [x] developer-access
- [x] developer-dot-net
- [x] developer-general
- [x] developer-internet
- [x] developer-sharepoint
- [x] developer-sql-reporting-services
- [x] developer-sql-server
- [x] developer-xsl
- [x] images
- [x] rules
- [x] ssw-logo
- [x] support
- [x] templates
- [x] wise-setup

**Comment by Calinator444** [comment]
@wicksipedia  I've noticed this file doesn't exist inside the v1 repo I've also tried checking dev ops. Should we still include them in the archive?

https://www.ssw.com.au/ssw/Standards/BetterSoftwareSuggestions/WaitingForSugggestionsToMoveToSharePoint/browse.aspx
https://ssw.com.au/ssw/Standards/WiseSetup/browse.aspx



![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/3cd4002e-dd7f-47a0-9151-3d3a33c6233d)

**Comment by tiagov8** [comment]
Hi @Calinator444 @wicksipedia 

I've converted the 2 suggestions to [bettersoftwaresuggestion.com](https://bettersoftwaresuggestions.com/):

- https://bettersoftwaresuggestions.com/microsoft/visual-studio-gallery/can-we-have-an-official-location-for-bugs/
- https://bettersoftwaresuggestions.com/microsoft/visual-studio-gallery/help-tfs-branding/

This means we can get rid of https://www.ssw.com.au/ssw/Standards/BetterSoftwareSuggestions/WaitingForSugggestionsToMoveToSharePoint/VSGallery.aspx

**Comment by Calinator444** [comment]
@tiagov8 Noted, I've got the Standards pages pretty much good to go on a separate branch so I'll just remove the VSGallery page

**Comment by Calinator444** [comment]
@wicksipedia 
(Using this comment to keep track of which pages we should nuke and why)

https://www.ssw.com.au/ssw/Standards/DeveloperGeneral/SuburbCombo.aspx - Page is blank on the live site. The aspx page suggests this is supposed to run an SQL query (See screenshot below)

![Image](https://github.com/SSWConsulting/SSW.Website/assets/65635198/ed77feab-aec7-4923-8dea-fd7d569b201d)
- [x] Approved by Wicksy

https://www.ssw.com.au/ssw/Standards/Rules//RulesToBetterInterfaces-Wizard.aspx - is a redirect

- [x] Approved by Wicksy


-https://www.ssw.com.au/ssw/Standards/DeveloperXSL/rptCustomerOrder.htm This page is blank due to what appears to be a javascript error, I couldn't find a working variant on the way back machine

- [x] Approved by Wicksy

**Comment by Calinator444** [comment]
@wicksipedia 
(Using this to keep track of broken pages that we could keep)


https://www.ssw.com.au/ssw/Standards/DeveloperXSL/rptCustomerOrder.htm This page is blank due to what appears to be a javascript error, I could pull a copy from the wayback machine

- [ ] Approved by Wicksy

**Comment by Calinator444** [comment]
@wicksipedia I've checked all of the pages that have been ported. My comments above explain which pages I think we should zz/fix andy why.

**Comment by Calinator444** [comment]
See done video here, new PBIs will need to be created to fix the archive banner links for the relevant pages and set up front door redirects

https://youtu.be/3knN7xJZrAo
