### ISSUE TITLE
♻️ Megamenu - Update menu.json for consulting pages

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.Website#263]
The consulting pages we have updated in the v3 site cannot be found using the mega menu, directing users to the old v1 consulting sites. Also, the sitemap (https://www.ssw.com.au/ssw/sitemap.xml) is generated based on this menu.json file, which would help in resolving #247.

- [ ] Update [`menu.json`](https://github.com/SSWConsulting/SSW.Website.Menu.json/blob/master/menu.json) with consulting pages for v2

**Comment by johnxu16** [comment]
Something may be helpful:

1. MegaMenu init menus from a local menu.json file in the src code https://github.com/SSWConsulting/SSW.MegaMenu/blob/main/lib/assets/data/menu.json
2. When it mounts, it fetches `menu.json` from https://sswconsulting.github.io/SSW.Website.Menu.json/menu.json

**Comment by KristenHu** [comment]
Done - https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/70

**Comment by bradystroud** [comment]
Hey @KristenHu 

This is not done.
All the consulting links need to be updated in the menu

Change from
https://www.ssw.com.au/ssw/Consulting/{{SERVICE_URI}}.aspx
to
https://www.ssw.com.au/consulting/{{SERVICE_URI}}


> **Warning**
> URLs might have changed in the migration - test for broken links


e.g. 
https://www.ssw.com.au/ssw/Consulting/Web-Applications.aspx
this url should become 
https://www.ssw.com.au/consulting/web-applications

Since our office pages are done, can you also update the links for them?
e.g.

change from
https://www.ssw.com.au/ssw/Company/Offices/Brisbane/
to
https://www.ssw.com.au/offices/brisbane


- [x] Update all consulting links
- [x] Update all offices links
- [x] Get PR approved by me

**Comment by KristenHu** [comment]
Done, this issue can be closed - https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/71

As per my conversation with Brady, website v3 missed the `consulting page -GPT`, so I added 2 issues to migrate GPT page and update it: #616  #617
