### ISSUE TITLE
Migration | Check remaining pages to archive

### ISSUE THREAD

**Issue by andrewwaltosssw** [SSWConsulting/SSW.Website#2696]
Task to check for any remaining pages that need to be archived
- [x] Check for unarchived pages
- [ ] Confirm with @wicksipedia what to do with them and do it

**Comment by Calinator444** [comment]
@wicksipedia 

I've generated a list of files that need to be ported. The good news is it looks like most of the pages that haven't been archived are newsletters, which are already on the live site so there's no need to port them.


I used a Python script that categorizes all of the pages as removed or archived depending on whether they've been marked as done in the progress repo. The list also flags any pages that have been marked as done but haven't been converted to html yet.

Finally I've included a list of pages in the repo that were referenced in the project file but not found in the repo since @amankumarrr  pointed out that there were pages missing in the repo that were still being served by the VM. Most of the links 404 but there's one or two pages that are probably worth porting. 



You can find the full list here: [progress.txt](https://github.com/user-attachments/files/15510633/progress.txt)
