### ISSUE TITLE
♻️ App Router migration - Articles

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.Website#3161]
### Description
To improve website performance and down-pay our tech debt, we need to migrate the articles pages (which are currently using pages routing) to app routing.

### Tasks
- [x] migrate ssw.com.au/articles to app routing
- [x] migrate ssw.com.au/articles[template] to app routing

**Comment by Calinator444** [comment]
I've migrated the pages to app routing, but performance is down on the article templates so I've moved these back into in progress. The performance is likely due to the pages using server-side rendering rather than static site generation, meaning the bage gets rebuilt on the server each time a request is sent.



**Figure**: **Poor performance on article templates**

**Comment by Calinator444** [comment]
As per our conversation during the sprint review, I've run a Semrush audit on the articles pages (i.e `https:www.ssw.com.au/articles/[articles]`) to determine if the slow loading times for the pages followed by the app router migration would be logged as issues

**Context**: the articles pages were loading slowly following the App Router migration due to the pages not being generated at build time (I have a fix for this here https://github.com/SSWConsulting/SSW.Website/pull/3344)

I ran 2 separate site audits:

- a full site audit on `ssw.com.au` 
- a site audit on `ssw.com.au/articles/[article]`


### Partial site audit
- `/articles` Pages were not crawled as issues as Semrush **does not** attempt to crawl pages that take longer than 5 seconds to load
- The low loading times were still flagged as issues as Semrush flags pages that it cannot crawl


### Full site audit
- The `/articles` pages did not appear in the site audit
- The `/articles` pages were also **not** listed under pages that couldn't be crawled
- It's unknown why the `/articles` pages did not appear in the site audit, but it may be that the project for the full site audit uses a different sitemap to the partial site audit


### Screenshots
![Image](https://github.com/user-attachments/assets/6237e6bf-37fa-47da-8e41-451a7511de37)
**Figure**: **Slow pages appearing as issues during the partial site audit**
<br>
![Image](https://github.com/user-attachments/assets/73be75b3-d60c-4234-8533-c354e1c2d198)
**Figure** **No slow pages flagged during the full site audit**

**Comment by Calinator444** [comment]
**Done** - I've updated the articles pages to be generated statically, the load times are dramatically shorter now.
