### ISSUE TITLE
✨ Customer Insight Journey - CRM

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Website#3288]
@wicksipedia 

**Describe the solution you'd like**

Currently, we rely on Clarity and Google Analytics to track page views, but these tools provide only anonymous data, so we're unable to identify individual users.

Customer Insight Journey (CIJ) offers a solution to bridge this gap. By capturing the user's email through a form submission, CIJ will enable us to identify users and match their interactions with existing records in our CRM.

As per my conversation with @louisroa8189, our plan is to use the `Contact Page View` trigger in CIJ to capture data from website form submissions, allowing us to track page views and associate them with specific contacts in the CRM.

Tasks:

- [ ] Create a Proof of Concept (POC) on CIJ
- [ ] Add email verification on functionality (once POC is approved)

**Comment by Calinator444** [comment]
I've tested this by triggering the Contact Page View trigger on the articles page, and then hooking that event up with a customer journey that sends the the customer in CUSTOMER_ID an email.

The emails failed to send because I didn't get permission from either myself or Seth to send the email, but I've managed to trigger the event locally from the app. 

![Image](https://github.com/user-attachments/assets/e5918d0b-fe21-482a-af0b-0565a938dbe6)
**Figure**: **Failed emails from customer journey**

![Image](https://github.com/user-attachments/assets/938c7634-57b0-4ac0-be99-93ba87564929)
**Figure**: **Code to call the trigger on the front end**

**Comment by Calinator444** [comment]
I've managed to track page visits on my local machine, but if we want to track interactions for specific users we may need to configure a customer insights landing page (See [link](https://learn.microsoft.com/en-us/dynamics365/customer-insights/journeys/track-online-behavior#set-up-website-tracking-and-read-results)). The page URL also appears to be missing from the results, which is likely a configuration issue.

![Image](https://github.com/user-attachments/assets/c7e5353d-5ffe-47f5-8232-c4a28a07bfc5)
**Figure**: **Website visits at the date of writing**

I did some troubleshooting and I could see cookies being written to my machine in Google Chrome's dev tools, so this doesn't appear to be an issue with cookies.

**Comment by Calinator444** [comment]
Triggers also do not appear to show up in the User's interaction time line unless they trigger a customer Journey

![Image](https://github.com/user-attachments/assets/9ab005f1-a03d-42ff-9bfa-b9136dac11a4)

**Comment by Calinator444** [comment]
I was able to get page visits appearing on Customer Insights Journeys from my local machine but I'm unsure why the page address was blank. I left a post in the Dynamics 365 Community forum regarding this. I asked Louis and he said to just leave the issue for now. 

Here's my post on the community forum https://community.dynamics.com.mcas.ms/forums/thread/details/?threadid=80e9a059-87a1-ef11-8a69-7c1e525799fb



![Image](https://github.com/user-attachments/assets/5a24e87a-6457-4276-877d-cf39648f55c2)

**Comment by Calinator444** [comment]
As per my conversation with Louis and @wicksipedia we'll be parking this for now.

**Comment by Calinator444** [comment]
I've created a thread on the Microsoft forums regarding being unable to see the page address

https://community.dynamics.com.mcas.ms/forums/thread/details/?threadid=80e9a059-87a1-ef11-8a69-7c1e525799fb

**Comment by jeoffreyfischer** [comment]
Closing this issue as per my conversation with @louisroa8189 

> Hi Jeoffrey, I had serious concerns about our approach to identifying anonymous sessions  (the whole point of a tracking script). Without a proper login/signup process, we're forced to rely solely on form submissions with names and emails - which I believe is far from ideal. This creates two major problems:
Without email verification, matching and updating records in Dynamics CRM is extremely risky. We could easily end up tracking the wrong users since we have no way to verify if they're providing their actual email addresses.
To make matters more complicated, we might lose access to Customer Insights Journeys by year-end since it'll no longer be included as a Microsoft benefit. Having to pay for it separately would need careful consideration.
