### ISSUE TITLE
✨ Develop the Image-Text Block Component

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Website#3316]
cc @wicksipedia @isaaclombardssw @UlyssesMaclaren @adamcogan @miichaelsmedley @louisroa8189 

**Description:**
Develop the Image-Text Block component for the Consulting Pages. This component should be highly flexible, allowing users to customise various fields (e.g., text, layout, buttons, icons, images). To ensure the UI remains clean and intuitive, group related options together (e.g., all button customisation options like text, link, and style under a single section) and use toggles to hide/show optional fields or elements. The design should prioritise usability and clarity.

**Acceptance Criteria:**
- The Image-Text Block component includes the following customisation options:

> - Layout Selector (Text-Image, Image-Text, No Image)
> - Background Selector (Transparent, Grey-700, Gradient 1/2/3/4)
> - Label 1
>   - Icon Selector
>   - Text Field
> - Heading Text Field
> - Description Text Field
> - Label 2 & Label 3
> - List
>   - Icon Selector (Per Item)
>   - Text Field (Per Item)
>   - Layout Selector (1-col, 2-col)
> - Button 1 & Button 2
>   - Before Icon Selector
>   - Text & Link Field
>   - After Icon Selector
>   - Style Selector (Primary, Secondary)
> - Lead Catcher (accepts email)
>   - Placeholder Text Field
>   - Button Text Field
> - Image File Uploader + Alt Text

- Fully responsive across desktop, tablet, and mobile
- Works seamlessly on all major browsers (Chrome, Firefox, Safari, Edge)
- Each field includes optional descriptions with links to relevant docs (e.g., Content Creator Guide)
- Fields can be enabled or disabled for flexibility
- Customisation options are grouped logically for a clean, easy-to-use interface
- Code is ready for theming (e.g., Light/Dark modes, custom colours – [see linked PBI](https://github.com/SSWConsulting/SSW.Website/issues/3300))
- Tested and approved by Wicksy, Louis and Betty

**Tasks**
- [ ] TODO - Developer to update

![Image](https://github.com/user-attachments/assets/afa02492-3a16-4ee6-9f40-9e2bd3edb323)
**Figure: Full Component - Desktop**

![Image](https://github.com/user-attachments/assets/bcfa47da-08c3-459f-b938-db91f2b92c70)
**Figure: Full Component - Mobile**

![Image](https://github.com/user-attachments/assets/b081658a-b413-4dc7-b863-264ac8455ada)
**Figure: Use Case - Hero Section**

![Image](https://github.com/user-attachments/assets/714b1411-cd71-4d58-804f-589549bdd9e2)
**Figure: Use Case - Benefits**

![Image](https://github.com/user-attachments/assets/898e5514-4840-4406-a982-fb6bbd20a0ca)
**Figure: Use Case - Experts**

![Image](https://github.com/user-attachments/assets/be81d2a8-33bb-48dd-899c-9485bf771ebf)
**Figure: Use Case - Single Case Study**

![Image](https://github.com/user-attachments/assets/b28ec8b9-6804-47b7-9a94-ec325e41f0b9)
**Figure: Use Case - CTA**

**Comment by isaaclombardssw** [comment]
This is still in progress – the schema's pretty much complete and I just have the component to do now.

There were one or two hold-ups including finding a bug with rich-text field embedded object lists, which I've done a minimal repro for and flagged with TinaCMS (see https://github.com/tinacms/tinacms/issues/5323)

Sneak peek of the schema:
![Image](https://github.com/user-attachments/assets/72dc1785-9f06-49f5-aa27-51b510b54a89)
![Image](https://github.com/user-attachments/assets/8f714fa8-2dba-4bb4-a4ba-50c710834775)

**Comment by jeoffreyfischer** [comment]
TODO: Check how much those icons increase the bundle size

**Comment by isaaclombardssw** [comment]
The email capture portion has been extracted into PBI #3360 after a conversation with Betty, Louis and Caleb (currently we aren't sure about the usage).

**Comment by isaaclombardssw** [comment]
As per my conversation with Betty/Wicksie, fade-in on scroll animation can be added (similar to current site animations).

**Comment by isaaclombardssw** [comment]
The bundle size issue is the last thing Caleb and I are trying to troubleshoot before this is ready for review – other than that you can see #3369 for the implementation and staging env.

**Comment by Calinator444** [comment]
We found that importing the icons for the icon picker was adding ~700kib to our bundle size. We're working on adding an endpoint that we're using to serve the icons instead so that they won't be imported into our page bundle.

![Image](https://github.com/user-attachments/assets/0936d351-991a-4f8c-ae4e-046b6ea48821)

**Comment by isaaclombardssw** [comment]
Final update re: the icons – we've spent ~1 day on this problem in total between us. Since we don't want it continually blocking we've checked in with Matt and logged it as tech debt. Caleb spent a little more time so will draft the PBI (including brief context on what we've already tried and associated caveats).

**Comment by Calinator444** [comment]
I created a status update video for this component as well as the other consulting v2 components

https://youtu.be/eqW01sLJ0WE

**Comment by Calinator444** [comment]
I've created a PBI logging the icon picker bundle size as tech debt

https://github.com/SSWConsulting/SSW.Website/issues/3374

**Comment by Calinator444** [comment]
General improvement: I've fixed the layout shifting issues on the consultingv2 page. The way we had useTina initialized was triggering un-necessary re-renders, so I memorized the data for the page.

![Image](https://github.com/user-attachments/assets/081a2475-76db-477a-a9dc-eb211006126f)
**Figure**: **❌Page rebuilding due to state changes**

![Image](https://github.com/user-attachments/assets/3c9c55dc-7b43-4668-a6f2-4718c54bbe11)
**Figure**: **✅tina data memoized to prevent un-necessary re-renders**

**Comment by Calinator444** [comment]
In addition, all consulting page components  now have a toggle to enable or disable the fade in animations on scroll

![Image](https://github.com/user-attachments/assets/9df4c2f6-d26e-4d0f-baa0-c96cbce0f945)

**Comment by isaaclombardssw** [comment]
The toggle described above has been removed (initial viewport blocks will be shown, following blocks will fade in).

**Comment by Calinator444** [comment]
I have a PR Open which fixes the fade in effect for the background

As per my conversation with @louisroa8189 I've locked the aspect ratio for this effect to 16:9 since next Next's image component forces you to provide an image/width or to set the image dimensions to a fixed value.


https://github.com/SSWConsulting/SSW.Website/pull/3414


![Image](https://github.com/user-attachments/assets/ec4398fe-43fb-45f8-86fb-ec195735b02c)
**Figure**: **Fixed bleed effect for image**

**Comment by isaaclombardssw** [comment]
See our done video for more details – https://www.youtube.com/watch?v=YWSE8qX30Vw
