### ISSUE TITLE
🎥 Video - How to edit the SSW website

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#711]
As per my conversation with @adamcogan we need a video on how to edit the website.

Show how you login to Tina and create and update content

**Comment by bradystroud** [comment]
Done - https://youtu.be/f7M5rRnLtJo

Added to the wiki - https://github.com/SSWConsulting/SSW.Website-v3/wiki/Editing-the-website

**Comment by adamcogan** [comment]
Hey @bradystroud 

#1 If you want to create another version please do so.
   Practise you intro and closing. Ideally get a Test Pass from @wicksipedia or @leahy268 
#2 Otherwise, please move from Loom to YouTube on the SSW Channel
      zz the Loom version
#3 see below UX suggestions to create

Tips for next time:
* Setup - raise the camera - ideally at eye-level

* Setup - build the pain by referencing a couple of things you could not do in the old Gatsby and NetlifyCMS and what you will see. e.g. Make the change blind. PR, get approved and build. Wait 10 mins and see the output. Arrrrg "it is not correct". Rinse and repeat.
Note: Mention these points again in the summary.

* Setup - Show a SSW rule that explains the major steps 
   E.g.
   A: Understand the UX change desired
   B: Create a personal branch
   C: Use awesome UX TinaCMS to make the change
     And use Live Preview to check you are making the change you are expecting.
   * Explain get changes moved into main. 
     Create New Branch
     Select your personal branch 
     Review 4th tab: Files Changed
     Back to 1st tab: Conversation. Hit "Edit" then update:
      - Affected Routes
      - The Issue number
   "OK lets jump into a demo to see how to do this..."

* 1:03 small audio issue

* 1:10 before you click on something, say what you are going to do and what you are going to click. 
   e.g. "I need a branch so I can get it test before it goes live. So in the top left I will click the 3rd button. [click]"

* 1:30 #3 why so many branches - seems messy + check for consistency of names

* 1:31 wait for it to create the branch and then mention how long it took and edit the video for brevity.
  When you closed the pop-up form I was confused. 
  Instead use that time to mention a UX suggestion you would like
  e.g. I would like an animation in the top right. 
  Even better mention a UX metaphor that exists that is similar.
  Then goto the bettersoftwaresuggestions.com URL that has that suggestion listed. That should link to TinaCMS's GitHub issue.

* 1:32 FYI here I was confused - I did not know what branch we were looking at?

* 1:37 I see a 2nd "title" field, so that needs explaining

* 2:08 Now back to the original branch. Mention UX suggestion #2 that it should have the most recent PR at the top.
   So their UX should have a 2nd column with date created... and sorted descending, so the most recent PR is at the top. 
   Anyway tell them what branch name you are looking for, then go hunting for it. 

* 2:11 Mention UX suggestion #3. You are going to click on the branch and it should slowly move to the top via a little animation.

* 2:12 Mention UX suggestion #4. You want a button "Continue..." as clicking the top right hand "X" is usually associated with "Cancel" 

* Summary "Such less pain. I did xxx. A couple of UX minor UX issues. All-in-all a wonderful editing experience. Go start editing"

-a
www.adamcogan.com

**Comment by bradystroud** [comment]
v2 - https://youtu.be/2raGSgWC8sE

**Comment by bradystroud** [comment]
Feedback from the v2 

- Sharpen intro “let’s jump in!” 
    - 0:41
- Lets assume a scenario of “AI is blowing up, lets move the card”
- Cursor is small - talk them through cursor moves
- On the left is the Tina editor, on the right is the live web page
    - Pick a piece of text, show they are synced up
- UX suggestion - You shouldn’t be able to make changes on the main branch
- UX suggestion - show last commit user on branch name (won’t work for branches with no commits)
- Explain GitHub flow
    - Why do we need a branch?
- UX suggestion - Select or Create a branch
- I’ve just created a branch, and its going to take a while
- While we are waiting, lets look at a few things that annoy me
    - Problem 1, Problem 2
        - New column username
        - Slow
        - I have to close it and reopen
    - BTW/FYI I have an issue for all of these
    - Like them if you agree
    - Let me show you how they work, here’s a few issues I’ve created
    - Here’s a little summary of the ones I care about
    - Team is responsive, I’ve had good success getting them to fix things for me
    - They work on the things that effect the most users
- More descriptive of what’s changing
    - Tell them where to look
- Now we are happy with the changes
- We want to say “we are happy with this branch”
- Need to ask for a second set of eyes
- Don’t need to mention v3
- 125%
- I’m looking for the branch name… ai-…
- Name PR
- Fixed issue number
    - Replace with “NA”
- Screenshot - That’s on my clipboard…
- Now I press CMD-V
- Practise closing
    - Same as opening
    - Happy for comments

**Comment by bradystroud** [comment]
@adamcogan 
v3 - https://youtu.be/GczUMLHXfik

**Comment by bradystroud** [comment]
As per my conversation with @adamcogan , he test passed the v3

The TV team edited a v4 https://www.youtube.com/watch?v=zrQ07-a-BwY&t=0s
