### ISSUE TITLE
🐛 Consulting index error

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Website#899]
**Describe the bug**
When you load the consulting index page, there is an error.

**To Reproduce**
1. Go to `/consulting`

<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/e6343b80-5c87-4322-af6d-62b6b15aa212">

**Comment by bradystroud** [comment]
As per my conversation with @Harry-Ross , this was fixed with #898

I think we should investigate further and see if we can answer these questions

1. Why did it used to work?
2. Was there a change that broke it?
3. The issue is with the footer - why it was only failing on the consulting index page?
4. Do we need to depend on DayJS

**Comment by Harry-Ross** [comment]
Answer to Q1-3:
From my investigation, the reason why the /consulting route had a bug with .fromNow() function from the dayjs/plugin/relativeTime module, but not the other pages was because the UpcomingEvents component was imported by using the <Blocks> component, which contains dayjs.extend(relativeTime). This wasn't noticed as most of the pages have the <Blocks> component in the page, which therefore loaded UpcomingEvents and the DayJS module extension. I have fixed this by having a single source of truth in the root app file for which DayJS modules have been loaded, which should make it clear to both devs and the TypeScript compiler which modules are available for use in the project.

I found the desired configuration at https://github.com/iamkun/dayjs/issues/1577. This means that by using dayjs.extend(), each subsequent use of DayJS will have the plugin used with the function.

4. We do need DayJS, as it formats the relative time in words (i.e. 1 hour ago, 6 years ago)
